### ISSUE TITLE
Add way to disable cache or use other caching libraries

### ISSUE THREAD

**Issue by bd-charu** [seriaati/enka-py#73]
Please add a way to use common libraries for caching like memcached or redis. Or allow user to disable by setting the cache to None.

**Comment by seriaati** [comment]
Added in v2.3.0, see [examples](https://github.com/seriaati/enka-py/blob/main/examples/cache.py) and [documentation](https://github.com/seriaati/enka-py/wiki/Client-Parameters#cache)
